import { Poppins } from 'next/font/google'

import type { Metadata } from 'next'

import { cn } from '@/lib/utils'

import './globals.css'

import Header from '@/components/layout/header'

const poppinsSans = Poppins({
  variable: '--font-poppins-sans',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'fallback',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={cn('h-full', 'antialiased', poppinsSans.variable, 'font-poppins-sans')}
    >
      <body className="flex min-h-full flex-col bg-[##FAFAFA]">
        <Header />
        {children}
      </body>
    </html>
  )
}
