import { Poppins } from 'next/font/google'

import type { Metadata } from 'next'

import { cn } from '@/lib/utils'

import '../globals.css'

import { NextIntlClientProvider } from 'next-intl'
import { getLocale } from 'next-intl/server'
import { Toaster } from 'sonner'

import { routing } from '@/i18n/routing'
import { ReactQueryProvider } from '@/providers/react.query'
import { SocketProvider } from '@/providers/socket.provider'

const poppinsSans = Poppins({
	variable: '--font-poppins-sans',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
	display: 'fallback',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export function generateStaticParams() {
	return routing.locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
	children,
}: LayoutProps<'/[locale]'>) {
	const locale = await getLocale()

	return (
		<html
			lang={locale}
			className={cn(
				'h-full',
				'antialiased',
				poppinsSans.variable,
				'font-poppins-sans',
			)}
		>
			<body className="min-h-full bg-[#FAFAFA]">
				<NextIntlClientProvider>
					<ReactQueryProvider>
						<SocketProvider>{children}</SocketProvider>
					</ReactQueryProvider>
					<Toaster position="top-center" />
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
